export enum PAGE_SIZE_VALUES {
  INITIAL_PAGE = 1,
  TOTAL_PAGE_SIZE = 10,
  TOTAL_NUMBER = 100,
  ELLIPSIS_LIMIT = 6,
  INDEX_LIMIT = 3,
  ELLIPSIS_PAGE = 4,
  TOTAL_PAGE_FOR_ELLIPSIS = 2,
}

export enum WIDTH_VALUES {
  MAX_WIDTH = 640,
  PRIMARY_WIDTH = 250,
  SECONDARY_WIDTH = 350,
}
